### ISSUE TITLE
Inlined CSS incomplete after update to 0.5.4

### ISSUE THREAD

**Issue by topaxi** [DockYard/ember-app-shell#20]
I have updated a website to ember-app-shell 0.5.4 and now a lot of selectors are missing in my `app-shell.html`

<details>
<summary>CSS output of 0.4.1</summary>

```css
@charset "UTF-8";
.header-icon > svg > path,
.logo-path {
  fill: currentColor;
}
.hamburglar,
a {
  color: inherit;
}
.menu {
  text-transform: uppercase;
}
.header-icon,
.logo {
  position: absolute;
  z-index: 1;
}
*,
::after,
::before {
  box-sizing: border-box;
}
:root {
  font-size: 16px;
}
body {
  margin: 0;
}
a {
  text-decoration: none;
}
.logo {
  top: 0;
  right: 0;
}
.logo > svg {
  width: 120px;
  height: 120px;
}
.header-icon {
  width: 3rem;
  height: 3rem;
  display: block;
  top: 15rem;
  right: 1rem;
}
.header-icon.email {
  top: 19rem;
}
@media screen and (max-width: 719px) {
  .header-icon {
    display: none;
  }
}
@media screen and (min-width: 640px) {
  .logo .rect {
    display: none;
  }
}
.animate-path,
.hamburglar,
.path-burger {
  width: 68px;
  height: 68px;
}
.liquid-container {
  position: relative;
  overflow: hidden;
}
.animate-path,
.burger-icon,
.hamburglar,
.path-burger {
  position: absolute;
}
.liquid-child {
  overflow: hidden;
}
.hamburglar {
  top: 1rem;
  left: 1rem;
  display: block;
  -webkit-appearance: none;
  outline: #000;
  border: 0;
  padding: 0;
  margin: 0;
  background-position: 0 0;
  background-repeat: initial initial;
}
.path-burger {
  top: 0;
  left: 0;
  display: none;
}
.animate-path {
  top: 0;
  left: 0;
}
.path-rotation {
  height: 34px;
  width: 34px;
  margin: 34px 34px 0 0;
}
.path-rotation::before {
  content: '';
  display: block;
  width: 30px;
  height: 34px;
  margin: 0 4px 0 0;
  background-color: currentcolor;
  background-position: initial initial;
  background-repeat: initial initial;
}
.path {
  stroke-dasharray: 240px;
  stroke-dashoffset: 240px;
  stroke-linejoin: round;
}
.burger-icon {
  top: 0;
  left: 0;
  padding: 20px 16px;
  height: 68px;
  width: 68px;
}
.burger-container {
  position: relative;
  height: 28px;
  width: 36px;
}
.burger-bun-bot,
.burger-bun-top,
.burger-filling {
  position: absolute;
  display: block;
  height: 4px;
  width: 36px;
  border-top-left-radius: 2px;
  border-top-right-radius: 2px;
  border-bottom-right-radius: 2px;
  border-bottom-left-radius: 2px;
  background-color: currentcolor;
  background-position: initial initial;
  background-repeat: initial initial;
}
.burger-ring,
.svg-ring {
  width: 68px;
  height: 68px;
}
.burger-bun-top {
  top: 0;
}
.burger-bun-bot {
  bottom: 0;
}
.burger-filling {
  top: 12px;
}
.burger-ring {
  position: absolute;
  top: 0;
  left: 0;
}
.svg-ring {
  stroke: currentColor;
}
s-mixcloud-player {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  height: 120px;
  background-color: #fff;
  background-position: initial initial;
  background-repeat: initial initial;
}
.menu {
  display: none;
  position: absolute;
  top: 4rem;
  left: 2rem;
  font-size: 2rem;
  line-height: 1.7;
  letter-spacing: 3px;
  z-index: 10;
}
@media screen and (min-width: 480px) {
  .menu {
    font-size: 3rem;
  }
}
.menu ul {
  margin-top: 2rem;
  list-style: none;
  padding: 0;
}
.menu li {
  opacity: 0;
}
.menu a {
  color: currentcolor;
  text-decoration: none;
}
:root {
  line-height: 1.34;
  -webkit-hyphens: auto;
  overflow-y: scroll;
}
.app-shell main {
  margin-top: 0;
}
.app-shell main img {
  margin-top: 10vh;
}
.app-shell + s-mixcloud-player {
  display: none;
}
.root {
  min-height: 100vh;
}
.root > header {
  position: relative;
}
.background-container {
  z-index: -1;
  position: fixed;
  left: 0;
  right: 0;
  height: 100vh;
}
.background-container .background,
.background-container .liquid-child {
  width: 100%;
  height: 100%;
}
.background {
  background-size: cover !important;
  background-attachment: fixed !important;
}
main {
  margin-top: 10rem;
  padding: 1rem;
  display: block;
}
main > .liquid-container > .liquid-child {
  min-height: 100%;
}
@media screen and (min-width: 640px) {
  main {
    margin-top: 15rem;
  }
}
@media screen and (min-width: 768px) {
  main {
    margin-top: 5rem;
  }
}
@media screen and (min-width: 1024px) {
  main {
    padding: 4rem 99px 4rem 4rem;
  }
}
```

</details>

<details>
<summary>CSS output of 0.5.4</summary>

```css
.logo-path {
  fill: currentcolor;
}
*,
::after,
::before {
  box-sizing: border-box;
}
:root {
  font-size: 16px;
}
body {
  margin: 0;
}
.logo > svg {
  width: 120px;
  height: 120px;
  transform-origin: right top 0;
  transform: scale(1.2);
}
@media screen and (min-width: 640px) {
  .logo .rect {
    display: none;
  }
}
@supports (display: grid) {
  .logo > svg {
    transform: scale(1);
  }
  @media screen and (min-width: 640px) {
    .logo > svg {
      transform: scale(1.667);
    }
  }
}
.liquid-container {
  position: relative;
  overflow: hidden;
  transform: translateY(0);
}
.liquid-child {
  overflow: hidden;
}
:root {
  line-height: 1.34;
  overflow-y: scroll;
  scroll-behavior: smooth;
}
.root {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
.root > header {
  position: relative;
}
.background-container {
  contain: strict;
  z-index: -1;
  position: fixed;
  left: 0;
  right: 0;
  height: 100vh;
}
.background-container .background,
.background-container .liquid-child {
  width: 100%;
  height: 100%;
}
.background {
  background-size: cover !important;
  background-attachment: fixed !important;
}
```

</details>

Used in https://github.com/topaxi/sarahtherad.com

**Comment by topaxi** [comment]
Seems like `penthouse` has different error correction code in newer versions, it has especially trouble with minified css as unminified seems to work fine.

**Comment by topaxi** [comment]
I've fixed the CSS that triggered a parse error in `penthouse` and the problem still persists. Sorry for the noise.

**Comment by ghost** [comment]
Does bumping  critical to 1.1.0 help? ¯\\_(ツ)_/¯

**Comment by topaxi** [comment]
No, this generates even less (and a bit different) css. 🙁 

<details>
<summary>0.5.4 with critical 1.1.0</summary>

```css
@charset "UTF-8";
.logo-path {
  fill: currentColor;
}
.root {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
.root > header {
  position: relative;
  padding: constant(safe-area-inset-top) constant(safe-area-inset-right)
    constant(safe-area-inset-left);
}
.background-container {
  contain: strict;
  z-index: -1;
  position: fixed;
  left: 0;
  right: 0;
  height: 100vh;
}
.background-container .background,
.background-container .liquid-child {
  width: 100%;
  height: 100%;
}
.background {
  background-size: cover !important;
  background-attachment: fixed !important;
}
```

</details>


Edit: Using https://jonassebastianohlsson.com/criticalpathcssgenerator/ I'm able to generate a correct critical CSS output. (This thing is linked in the `penthouse` repo)

**Comment by ghost** [comment]
Hmm, and what about pre 1.0 critical?

**Comment by topaxi** [comment]
0.5.4 with critical 0.9.1 gives me yet another output

<details>
<summary>0.5.4 with critical 0.9.1</summary>

```css
@charset "UTF-8";
.header-icon > svg > path,
.logo-path {
  fill: currentColor;
}
.hamburglar,
a {
  color: inherit;
}
.menu {
  text-transform: uppercase;
}
.header-icon,
.logo {
  position: absolute;
  z-index: 1;
}
.root {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
.root > header {
  position: relative;
  padding: constant(safe-area-inset-top) constant(safe-area-inset-right)
    constant(safe-area-inset-left);
}
.background-container {
  contain: strict;
  z-index: -1;
  position: fixed;
  left: 0;
  right: 0;
  height: 100vh;
}
.background-container .background,
.background-container .liquid-child {
  width: 100%;
  height: 100%;
}
.background {
  background-size: cover !important;
  background-attachment: fixed !important;
}
main {
  margin-top: 10rem;
  margin-right: constant(safe-area-inset-right);
  margin-left: constant(safe-area-inset-left);
  margin-bottom: constant(safe-area-inset-bottom);
  padding: 1rem;
  flex: 1;
  display: block;
}
main > .liquid-container {
  transform: none;
  flex: 1;
}
main > .liquid-container > .liquid-child {
  min-height: 100%;
}
@supports (display: grid) {
  main {
    display: flex;
  }
}
@media screen and (min-width: 640px) {
  main {
    margin-top: 15rem;
  }
}
@media screen and (min-width: 768px) {
  main {
    margin-top: 5rem;
  }
}
@media screen and (min-width: 1024px) {
  main {
    padding: 4rem 99px 4rem 4rem;
  }
}
```

</details>

The output HTML is correct in all cases though.. very strange 😕  

It's even missing the most obvious selectors which start with `.app-shell`.
